### PR TITLE
Added ru_ru.lang

### PR DESCRIPTION
**Pull request by TheDirectorX**

### CODE REVIEW

**Comment by MelanX** [comment]
Hi :) do you wanna have an icon rendered when this mod is installed? You can choose out of Livingwood, Livingrock and Manasteel. Here is an example:
example

**Comment by TheDirectorX** [comment]
It looks cool, but I think it will be superfluous.
[(﻿ ͡° ͜ʖ ͡°)](https://namemc.com/profile/DirectorX)

**Comment by MelanX** [comment]
Okay... what would be your favorite item of the mentioned ones above? In case it wouldn’t be superfluous ( ͡° ͜ʖ ͡°)

**Comment by TheDirectorX** [comment]
### Livingwood

**Pull request merged**
